apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: caixa-mercado
  labels:
    app: mysql
    projeto: caixa-mercado
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  # storageClassName pode ser omitido para usar o default do cluster
  # storageClassName: standard
