apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: caixa-mercado
  labels:
    app: mysql
    projeto: caixa-mercado
type: Opaque
# Valores em base64. Para gerar: echo -n "valor" | base64
# Substitua pelos valores reais antes de aplicar com kubectl
stringData:
  root-password: root_secret
  user: mercado_user
  password: mercado_pass
  database: mercado_at
